02_Framework/01_Django/01_django/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('greeting/', views.greeting, name='greeting'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('show/<name>/', views.show, name='show'),  # <>변수 같은거임, <str:name> <int:key> <- 라우터이고 str이 default값이고 생략가능
]

02_Framework/01_Django/01_django/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
]

02_Framework/01_Django/01_django/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('index/', views.index, name='index'),
]

02_Framework/01_Django/01_django/articles/models.py
from django.db import models

# Create your models here.

02_Framework/01_Django/01_django/pages/models.py
from django.db import models

# Create your models here.

02_Framework/01_Django/01_django/articles/views.py
import datetime
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'articles/index.html')  # 무조건 request 첫번째, 두번째는 어디로, 세번째부터? 데이터


def greeting(request):
    today = datetime.datetime(2022, 8, 8, 10, 2)
    context = {
        'name': 'justin',
        'foods': ['apple', 'chicken', 'burger'],
        'today' : today
    }
    return render(request, 'articles/greeting.html', context)

def throw(request):
    return render(request, 'articles/throw.html')

def catch(request):
    # print(request)
    # print(type(request))
    # print(request.GET.get('message'))
    department = request.GET.get('department')
    name = request.GET.get('name')

    if department == '대전 2반':
        if name == '김영주':
            message = '교수님이시군요!'
        else:
            message = '교육생이시군요!'
    else:
        message = '다른 반이시군요!'

    context = {
        'message':message,        
    }
    return render(request, 'articles/catch.html', context)

def show(request, name):
    context = {
        'name':name
    }
    return  render(request, 'articles/show.html', context)

02_Framework/01_Django/01_django/pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'pages/index.html')

02_Framework/01_Django/01_django/articles/templates/articles/catch.html
{% extends 'base.html' %}

{% block content %}
  <h1>당신의 결과는</h1>
  <h2>{{ message }}<h2>
  <a href="{% url 'articles:throw' %}">다시 던지러가자.</a>
  <a href="{% url 'articles:index' %}">홈 화면으로 이동</a>
{% endblock %}

02_Framework/01_Django/01_django/articles/templates/articles/greeting.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>greeting</title>
</head>
<body>
  <h1>안녕하세요. 저는 {{ name }} 입니다.</h1>
  <p>제 이름의 길이는 {{ name|length }} 글자 입니다.</p>
  {% comment %} <p>제가 좋아하는 음식은 {{ food|join:" & " }} 입니다.</p>  {% endcomment %}
  
  {% for food  in foods %}
    {% if food|length > 6 %}
      <p>6글자 초과의 음식은 {{ food }}</p>
    {% endif %}
  {% endfor %}

    {% comment %} {% for food in foods %}
    <p>{{ forloop.counter0 }}번째 음식 {{ food }}</p>
  {% endfor %} {% endcomment %}

    {# <p>이것은 한 줄짜리 주석입니다.</p> #}

    {% comment %} <p>이것은 여러줄 주석입니다.</p>
    <p>이것은 여러줄 주석입니다.</p> {% endcomment %}

  {% for food  in foods %}
    <p>{{ forloop.counter0 }}</p>

  {% empty %}
    <p>죄송합니다. 좋아하는 음식이 없네요.</p>
  {% endfor %}
  <p>{{ today|date:"Y년 m월 j일 (D) A h:i" }}</p>
  <a href={% url 'articles:index' %}>홈 화면으로 이동</a>
</body>
</html>

02_Framework/01_Django/01_django/articles/templates/articles/index.html
{% extends 'base.html' %}
{# 반드시 extends는 제일 위에 #}

{% block content %}
  <h1 class='text-danger'>만나서 반갑~</h1>
  <a href="{% url 'articles:greeting' %}">greeting</a>
  <a href="{% url 'articles:throw' %}">throw</a>
  
  <a href="{% url 'articles:index' %}">두번째 앱 index로 이동</a>
{% endblock content %}

{# 이게 템플릿 상속이다, 맞는 블럭에 끼워주겟다 이런거임 그리고 endblock 뒤에는 지워도 상관없음 #}

02_Framework/01_Django/01_django/articles/templates/articles/show.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ name }}</h1>
  <a href={% url 'articles:index' %}>홈 화면으로 이동</a>
{% endblock %}

02_Framework/01_Django/01_django/articles/templates/articles/throw.html
{% extends 'base.html' %}

{% block content %}
  <h3>당신의 소속과 이름을 적어주세요</h3>
  <form action='/catch/' method='GET'>
    <label for='department'>소속<label>
    <input type='text' id='department' name='department'>
    <br>
    <label for='name'>이름<label>
    <input type='text' id='name' name='name'>
    <input type='submit'>
  </form>
  <a href={% url 'articles:index' %}>홈 화면으로 이동</a>
{% endblock %}

02_Framework/01_Django/01_django/pages/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>두번째 앱의 인덱스 페이지</h1>
{% endblock  %}