02_Framework/01_Django/02_django/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),  # 화면을 보여주는 기능
    path('<int:pk>/update/', views.update, name='update'),  # 실제 기능
]

02_Framework/01_Django/02_django/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # def __str__(self):
    #     return self.title

02_Framework/01_Django/02_django/articles/views.py
from django.shortcuts import render, redirect

from .models import Article

# Create your views here.
def index(request):
    # articles = Article.objects.all()[::-1]  # 이렇게하면 최신글부터 볼 수 있음
    articles = Article.objects.order_by('-pk')  # 큰거부터 나오게 하는거
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    
    article = Article(title=title, content=content)  # 1번방법
    article.save()

    # article = Article()  # 2번방법
    # article.title = title
    # article.content = content
    # article.save()

    # Article.objects.create(title=title, content=content)  # <-3번방법

    return redirect('articles:index')  # redirect는 경로 우회 저기로가!

def detail(request, pk):
    article = Article.objects.get(pk=pk)  # 오른쪽이 인자값
    context = {
        'article': article,
    }
    return render(request,'articles/detail.html', context)

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index')

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/edit.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:detail', article.pk)

02_Framework/01_Django/02_django/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
  <h3>{{ article.pk }}번째 글</h3>
  <hr>
  <p>제목 : {{ article.title }}</p>
  <p>내용 : {{ article.content }}</p>
  <p>작성시간 : {{ article.created_at }}</p>
  <p>수정시간 : {{ article.updated_at }}</p>
  <hr>
  <a href="{% url 'articles:edit' article.pk %}">EDIT</a>
  <form action='{% url 'articles:delete' article.pk %}' method='POST'>
    {% csrf_token %}
    <input type='submit' value='DELETE'>
  </form>
  <a href="{% url 'articles:index' %}">INDEX</a>
{% endblock content %}

02_Framework/01_Django/02_django/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
  <h1>EDIT</h1>
  <form action="{% url 'articles:update' article.pk %}" method='POST'>
    {% csrf_token %}
    <label for='title'>Title: </label>
    <input type ='text' name='title' value="{{ article.title}}"><br>
    <label for='content'>Content: </label>
    <textarea name='content'>{{ article.content }}</textarea><br>
    <input type='submit'>
  </form>
{% endblock content %}

02_Framework/01_Django/02_django/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Article</h1>
  <a href="{% url 'articles:new' %}">NEW</a>
  <hr>
  {% for article in articles %}
    <p>글 번호: {{ article.pk }}</p>
    <p>글 제목: {{ article.title }}</p>
    <p>글 내용: {{ article.content }}</p>
    <a href="{% url 'articles:detail' article.pk %}">DETAIL</a>  {# article.pk는 필요한 인자 넘겨주는 거임, 따옴표 없음 #}
    <hr>
  {% endfor %}
{% endblock content %}

02_Framework/01_Django/02_django/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>New</h1>
  <form action="{% url 'articles:create' %}" method='POST'>
    {% csrf_token %}  {# 내가 관리자라는   증거(내가 보낸거라는 증거)를 같이 보내줄게!, post를 쓸때는 무조건 csrf_token을 써야한다! #}
    <label for='title'>Title: </label>
    <input type='text' name='title'><br>
    <label for='content'>Content: </label>
    <textarea name='content'></textarea><br>
    <input type='submit'>
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock content %}